Ekaterina N: homework_5 completed
eugene-okulik/Ekaterina_N pull request #4
Opened 2024-06-21 12:16 UTC by PrincessOfAmber

2024-06-21 14:52 UTC, eugene-okulik requested changes

2024-06-21 14:52 UTC, eugene-okulik commented on homework/ekaterina_nizhegorodova/homework_5/task2.py
> +number_index = returned.index("42")
Если еще в момент написания программы мы знаем, что в строке будет число 42, то мы можем написать просто print(42 + 10)  
Заморочка в том, чтобы найти в этой строке число, каким бы оно там ни было. Для этого нужно найти в этих строках что-то одинаковое: количество символов перед числом разное; количество символов в числе тоже разное. Но есть в структуре всех строк что-то одинаковое и на это можно опереться.

2024-06-21 15:11 UTC, PrincessOfAmber commented on homework/ekaterina_nizhegorodova/homework_5/task2.py
> +number_index = returned.index("42")
так? или подход в том, что индекс для третьего ответа тоже не должен пересохраняться, и все должно быть универсально?

2024-06-23 12:06 UTC, eugene-okulik approved these changes

2024-06-23 12:06 UTC, merged