Ekaterina N: homework_9 completed
eugene-okulik/Ekaterina_N pull request #8
Opened 2024-06-29 13:40 UTC by PrincessOfAmber

2024-06-29 14:06 UTC, eugene-okulik requested changes

2024-06-29 14:06 UTC, eugene-okulik commented on homework/ekaterina_nizhegorodova/homework_9/task2.py
Отлично. Осталось доделать задание )))
> Распечатайте из нового списка самую высокую температуру самую низкую и среднюю.

2024-06-29 15:03 UTC, PrincessOfAmber commented
неловко вышло))) минская жара мозги попортила)

2024-06-30 08:19 UTC, eugene-okulik approved these changes

2024-06-30 08:19 UTC, merged